version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "slaskawi"
      - "lsierant"
      - "mircea-cosbuc"
      - "nammn"
      - "Julien-Ben"
