version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
