#!/usr/bin/env sh

# This should be copied to .git/hooks/pre-commit

echo "executing pre-commit hook"
if ! type goimports &> /dev/null; then
    echo "Installing goimports"
    GO111MODULE=off go get golang.org/x/tools/cmd/goimports
fi

# Formats each go file that was changed.
for file in $(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
do
    goimports -w "${file}"
    git add "$file"
done


# Black linting of every file that was changed
for file in $(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')
do
    black -q "$file"
    git add "$file"
done
