ignore:
  - "*.md"

functions:
  clone:
    - command: subprocess.exec
      type: setup
      params:
        command: "mkdir -p mongodb-kubernetes-operator"
    - command: git.get_project
      type: setup
      params:
        directory: mongodb-kubernetes-operator

  go_test:
    - command: subprocess.exec
      type: test
      params:
        include_expansions_in_env:
          - version_id
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/run_unit_tests.sh

  setup_operator_sdk:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://github.com/operator-framework/operator-sdk/releases/download/v0.15.1/operator-sdk-v0.15.1-x86_64-linux-gnu
          FILENAME: operator-sdk
          DIR: ${workdir}/bin

  setup_kubernetes_environment:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://storage.googleapis.com/kubernetes-release/release/v1.15.4/bin/linux/amd64/kubectl
          FILENAME: kubectl
          DIR: ${workdir}/bin

    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
          FILENAME: kind
          DIR: ${workdir}/bin

    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/create_kind_cluster.sh
        env:
          KUBECONFIG: ${workdir}/kube_config

  run_e2e_test:
    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        include_expansions_in_env:
          - version_id
          - test
        binary: scripts/ci/run_test.sh
        env:
          KUBECONFIG: ${workdir}/kube_config

  build_and_push_image:
    - command: subprocess.exec
      type: setup
      params:
        include_expansions_in_env:
          - version_id
          - quay_user_name
          - quay_password
          - image
          - dockerfile
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/build_and_push_image.sh

tasks:
  - name: build_operator_image
    priority: 60
    exec_timeout_secs: 600
    commands:
      - func: clone
      - func: build_and_push_image
        vars:
          dockerfile: docker/Dockerfile.operator
          image: quay.io/mongodb/community-operator-dev:${version_id}

  - name: build_e2e_image
    priority: 60
    exec_timeout_secs: 600
    commands:
      - func: clone
      - func: build_and_push_image
        vars:
          dockerfile: docker/Dockerfile.e2e
          image: quay.io/mongodb/community-operator-e2e:${version_id}

  - name: unit_tests
    commands:
      - func: clone
      - func: go_test

  - name: e2e_test_replica_set
    commands:
      - func: clone
      - func: setup_kubernetes_environment
      - func: run_e2e_test
        vars:
          test: replica_set

  - name: e2e_test_replica_set_readiness_probe
    commands:
      - func: clone
      - func: setup_kubernetes_environment
      - func: run_e2e_test
        vars:
          test: replica_set_readiness_probe


buildvariants:
  - name: go_unit_tests
    display_name: go_unit_tests
    run_on:
      - ubuntu1604-build
    tasks:
      - name: unit_tests

  - name: e2e_tests
    display_name: e2e_tests
    run_on:
      - ubuntu1604-build
    depends_on:
      - name: build_operator_image
        variant: init_test_run
      - name: build_e2e_image
        variant: init_test_run
    tasks:
      - name: e2e_test_replica_set
      - name: e2e_test_replica_set_readiness_probe

  - name: init_test_run
    display_name: init_test_run
    run_on:
      - ubuntu1604-build
    tasks:
      - name: build_operator_image
      - name: build_e2e_image
