ignore:
  - "*.md"

functions:
  setup_virtualenv:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/setup_virtualenv.sh

  clone:
    - command: subprocess.exec
      type: setup
      params:
        command: "mkdir -p mongodb-kubernetes-operator"
    - command: git.get_project
      type: setup
      params:
        directory: mongodb-kubernetes-operator

  # upload_e2e_logs has the responsibility of dumping as much information as
  # possible into the S3 bucket
  upload_e2e_logs:
    - command: s3.put
      params:
        aws_key: ${community_aws_access_key_id}
        aws_secret: ${community_aws_secret_access_key}
        local_files_include_filter_prefix: mongodb-kubernetes-operator/logs/
        local_files_include_filter:
          - e2e/*.txt
          - e2e/*.log
          - e2e/*.json
        region: us-east-1
        remote_file: logs/${task_id}/${execution}/
        bucket: community-operator-e2e-logs
        permissions: public-read
        content_type: text/plain

  # This is a blocker for the release process. It will *always* fail and needs to be overriden
  # if the release needs to proceed.
  release_blocker:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/release_blocker

  setup_kubernetes_environment:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://storage.googleapis.com/kubernetes-release/release/v1.15.4/bin/linux/amd64/kubectl
          FILENAME: kubectl
          DIR: ${workdir}/bin

    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
          FILENAME: kind
          DIR: ${workdir}/bin

  create_kind_cluster:
    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/create_kind_cluster.sh
        env:
          KUBECONFIG: ${workdir}/kube_config

  run_e2e_test:
    - command: subprocess.exec
      type: test
      params:
        working_dir: mongodb-kubernetes-operator
        env:
          KUBECONFIG: ${workdir}/kube_config
        include_expansions_in_env:
          - version_id
          - test
          - clusterwide
        binary: scripts/ci/run_test.sh


  build_and_push_image:
    - command: subprocess.exec
      type: setup
      params:
        include_expansions_in_env:
          - version_id
          - quay_user_name
          - quay_password
          - image
          - image_type
          - expire_after
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/build_and_push_image.sh

  release_docker_image:
    - command: subprocess.exec
      type: system
      params:
        working_dir: mongodb-kubernetes-operator
        include_expansions_in_env:
          - version_id
          - quay_user_name
          - quay_password
          - old_image
          - new_image
          - image_type
        command: scripts/ci/run_image_release.sh

task_groups:
- name: e2e_test_group
  max_hosts: 4
  setup_group:
    - func: clone
    - func: setup_virtualenv
    - func: setup_kubernetes_environment
  setup_task:
    - func: create_kind_cluster
  tasks:
    - e2e_test_replica_set
    - e2e_test_replica_set_readiness_probe
    - e2e_test_replica_set_scale
    - e2e_test_replica_set_scale_down
    - e2e_test_replica_set_change_version
    - e2e_test_feature_compatibility_version
    - e2e_test_feature_compatibility_version_upgrade
    - e2e_test_replica_set_multiple
#    - e2e_test_replica_set_tls # TODO: flaky test, fix and uncomment in CLOUDP-76190
    - e2e_test_replica_set_tls_upgrade
    - e2e_test_replica_set_tls_rotate
    - e2e_test_statefulset_arbitrary_config
    - e2e_test_statefulset_arbitrary_config_update
    - e2e_test_replica_set_mongod_config
    - e2e_test_replica_set_cross_namespace_deploy
    - e2e_test_replica_set_custom_role
  teardown_task:
    - func: upload_e2e_logs

tasks:
  - name: build_operator_image
    priority: 60
    exec_timeout_secs: 600
    commands:
      - func: clone
      - func: setup_virtualenv
      - func: build_and_push_image
        vars:
          image_type: operator
          image: quay.io/mongodb/community-operator-dev:${version_id}
          expire_after: 48h

  - name: build_e2e_image
    priority: 60
    exec_timeout_secs: 600
    commands:
      - func: clone
      - func: setup_virtualenv
      - func: build_and_push_image
        vars:
          image: quay.io/mongodb/community-operator-e2e:${version_id}
          image_type: e2e
          expire_after: 48h

  - name: build_prehook_image
    priority: 60
    exec_timeout_secs: 600
    commands:
      - func: clone
      - func: setup_virtualenv
      - func: build_and_push_image
        vars:
          image: quay.io/mongodb/community-operator-version-upgrade-post-start-hook:${version_id}
          image_type: versionhook
          expire_after: 48h

  - name: e2e_test_feature_compatibility_version
    commands:
      - func: run_e2e_test
        vars:
          test: feature_compatibility_version

  - name: e2e_test_feature_compatibility_version_upgrade
    commands:
      - func: run_e2e_test
        vars:
          test: feature_compatibility_version

  - name: e2e_test_replica_set
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set

  - name: e2e_test_replica_set_readiness_probe
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_readiness_probe

  - name: e2e_test_replica_set_scale
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_scale

  - name: e2e_test_replica_set_scale_down
    exec_timeout_secs: 3600
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_scale_down

  - name: e2e_test_replica_set_change_version
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_change_version

  - name: e2e_test_replica_set_multiple
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_multiple

  - name: e2e_test_replica_set_tls
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_tls

  - name: e2e_test_replica_set_tls_upgrade
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_tls_upgrade

  - name: e2e_test_replica_set_tls_rotate
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_tls_rotate

  - name: e2e_test_statefulset_arbitrary_config
    commands:
      - func: run_e2e_test
        vars:
          test: statefulset_arbitrary_config

  - name: e2e_test_statefulset_arbitrary_config_update
    commands:
      - func: run_e2e_test
        vars:
          test: statefulset_arbitrary_config_update

  - name: e2e_test_replica_set_mongod_config
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_mongod_config

  - name: e2e_test_replica_set_cross_namespace_deploy
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_cross_namespace_deploy
          clusterwide: true

  - name: e2e_test_replica_set_custom_role
    commands:
      - func: run_e2e_test
        vars:
          test: replica_set_custom_role

  - name: release_blocker
    commands:
      - func: clone
      - func: release_blocker

  - name: release_operator
    commands:
      - func: clone
      - func: setup_virtualenv
      - func: release_docker_image
        vars:
          old_image: quay.io/mongodb/community-operator-dev
          new_image: quay.io/mongodb/mongodb-kubernetes-operator
          image_type: mongodb-kubernetes-operator

  - name: release_version_upgrade_hook
    commands:
      - func: clone
      - func: setup_virtualenv
      - func: release_docker_image
        vars:
          old_image: quay.io/mongodb/community-operator-version-upgrade-post-start-hook
          new_image: quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook
          image_type: version-upgrade-hook


buildvariants:
  - name: e2e_tests
    display_name: e2e_tests
    run_on:
      - ubuntu1604-build
    depends_on:
      - name: build_operator_image
        variant: init_test_run
      - name: build_e2e_image
        variant: init_test_run
      - name: build_prehook_image
        variant: init_test_run
    tasks:
      - name: e2e_test_group

  - name: init_test_run
    display_name: init_test_run
    run_on:
      - ubuntu1604-build
    tasks:
      - name: build_operator_image
      - name: build_e2e_image
      - name: build_prehook_image

  - name: release_blocker
    display_name: release_blocker
    run_on:
      - ubuntu1604-packer  # Note: cheapest machine I found
    tasks:
      - name: release_blocker

  - name: release_images_quay
    display_name: release_images_quay
    depends_on:
      - name: release_blocker
        variant: release_blocker
      - name: build_operator_image
        variant: init_test_run
      - name: build_prehook_image
        variant: init_test_run
    run_on:
      - ubuntu1604-test
    tasks:
    - name: release_operator
    - name: release_version_upgrade_hook
