ignore:
  - "*.md"

variables:
  - &go_options
    GO111MODULE: "on"
    GOFLAGS: "-mod=vendor"
    GOROOT: "/opt/golang/go1.13"
  - &go_bin
      "/opt/golang/go1.13/bin"


functions:
  clone:
    - command: subprocess.exec
      type: setup
      params:
        command: "mkdir -p mongodb-kubernetes-operator"
    - command: git.get_project
      type: setup
      params:
        directory: mongodb-kubernetes-operator

  go_test:
    - command: subprocess.exec
      type: test
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        command: "go test ./..."

  setup_operator_sdk:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://github.com/operator-framework/operator-sdk/releases/download/v0.15.1/operator-sdk-v0.15.1-x86_64-linux-gnu
          FILENAME: operator-sdk
          DIR: ${workdir}/bin

  run_test_locally:
    - command: subprocess.exec
      type: test
      params:
        add_to_path:
          - ${workdir}/bin
          - *go_bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/run_e2e_tests.sh
        env:
          KUBECONFIG: ${workdir}/kube_config
          <<: *go_options

  generate_k8s:
    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
          - *go_bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/generate_k8.sh

  setup_kubernetes_environment:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://storage.googleapis.com/kubernetes-release/release/v1.15.4/bin/linux/amd64/kubectl
          FILENAME: kubectl
          DIR: ${workdir}/bin

    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
          FILENAME: kind
          DIR: ${workdir}/bin

    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
          - *go_bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/create_kind_cluster.sh
        env:
          KUBECONFIG: ${workdir}/kube_config

  deploy_operator:
    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/deploy_operator.sh
        env:
          KUBECONFIG: ${workdir}/kube_config

tasks:
  - name: unit_tests
    commands:
      - func: clone
      - func: setup_operator_sdk
      - func: generate_k8s
      - func: go_test

  - name: e2e_test
    commands:
      - func: clone
      - func: setup_kubernetes_environment
      - func: setup_operator_sdk
      - func: generate_k8s
      - func: deploy_operator
      - func: run_test_locally

buildvariants:
  - name: go_unit_tests
    display_name: go_unit_tests
    run_on:
      - ubuntu1604-build
    tasks:
      - name: unit_tests

  - name: e2e_tests
    display_name: e2e_tests
    run_on:
      - ubuntu1604-build
    tasks:
      - name: e2e_test
