---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude-rules:
    - path: _test\.go
      linters:
      - dupl
      - gosec
      - goconst
      - golint
      text: "underscore"
    - path: ^pkg\/util\/envvar
      linters:
        - forbidigo
    - path: ^cmd\/(readiness|versionhook|manager)\/main\.go$
      linters:
        - forbidigo
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - rowserrcheck
    - gosec
    - unconvert
    - forbidigo
linters-settings:
  gosec:
    excludes:
      - G115
  forbidigo:
    forbid:
      - p: os\.(Getenv|LookupEnv|Environ|ExpandEnv)
        pkg: os
        msg: "Reading environemnt variables here is prohibited. Please read environment variables in the main package."
      - p: os\.(Clearenv|Unsetenv|Setenv)
        msg: "Modifying environemnt variables is prohibited."
        pkg: os
      - p: envvar\.(Read.*?|MergeWithOverride|GetEnvOrDefault)
        pkg: github.com/mongodb/mongodb-kubernetes-operator/pkg/util/envvar
        msg: "Using this envvar package here is prohibited. Please work with environment variables in the main package."
    # Rules with the `pkg` depend on it
    analyze-types: true

run:
  modules-download-mode: mod
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  # default concurrency is a available CPU number
  concurrency: 4
