checks:
  addAllBuiltIn: true

  #Reasons to exclude
  # non-existent-service-account because the service account is created in another file
  # minimum-three-replicas because the deployment contains only 1 replica of the operator
  # no-readiness-probe & no-liveness-probe because for now it brings nothing to add theses probes
  # because they will not check whether the operator is actually ready/living
  # run-as-non-root & no-read-only-root-fs because the security is managed somewhere else
  exclude:
  - "non-existent-service-account"
  - "minimum-three-replicas"
  - "no-liveness-probe"
  - "no-readiness-probe"
  - "run-as-non-root"
  - "no-read-only-root-fs"
  - "use-namespace"
