name: Run E2E
jobs:
  - template: setup
    if: github.event.pull_request.head.repo.full_name == 'mongodb/mongodb-kubernetes-operator'
    steps:
    - template: cancel-previous
    - template: checkout
    - template: setup-and-install-python
    - template: quay-login
    - template: build-and-push-development-images
  - template: tests
    steps:
    - template: cancel-previous
    - template: checkout
    - template: set-run-status
    - template: setup-and-install-python
    - template: setup-kind-cluster
    - template: run-test-matrix
    - template: save-run-status
    - template: dump-and-upload-diagnostics
  - template: e2e-success

events:
  - template: on-pull-request-master
  - template: on-push-master
  - template: workflow-dispatch
