{% extends "Dockerfile.template" %}

{% set base_image = "registry.access.redhat.com/ubi8/ubi-minimal" %}

{% block packages -%}
RUN microdnf install -y --disableplugin=subscription-manager --setopt=install_weak_deps=0 nss_wrapper
RUN microdnf install -y --disableplugin=subscription-manager curl \
    hostname tar gzip procps\
    && microdnf upgrade -y  \
    && rm -rf /var/lib/apt/lists/*

{% endblock -%}
