#!/usr/bin/env bash

#
# Exits with status code 1 if the git describe command prints "dirty".
# This is a mechanism to block evergreen release patches that are not clean.
#
# This grep code expects the git describe command to return a x.y.z pattern,
# or it fails.
#

git describe --dirty | grep -q -E "^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$"
