#!/usr/bin/env sh

echo "🚀"
echo "This is the Release Blocker Task. This task is set to always fail in order to block release operations."
echo "To release/publish the images you have to manually override dependencies on the release_* build variants."
echo "This can only be done on commits that have been tagged!"
echo "🚢"

# This command will always fail!
exit 1
