---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mongodb-tls
      caConfigMapRef:
        name: ca-issuer
    authentication:
      modes: ["X509", "SCRAM"]
      agentMode: "X509"
      agentCertificateSecretRef:
        name: my-agent-certificate
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - db: admin
          name: readWriteAnyDatabase
      scramCredentialsSecretName: my-scram
    - name: "CN=my-x509-authenticated-user,OU=organizationalunit,O=organization"
      db: "$external"
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - db: admin
          name: readWriteAnyDatabase


# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: password

