---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-prometheus
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"

  # You can expose metrics for Prometheus polling using the
  # `prometheus` entry.
  prometheus:
    # Metrics endpoint HTTP Basic Auth username
    username: <username>

    # Metrics endpoint HTTP Basic Auth password
    passwordSecretRef:
      name: metrics-endpoint-password

    # Optional, defaults to `/metrics`
    # metricsPath: /metrics

    # Optional defaults to 9216
    # port: 9216

    # Prometheus endpoint can be configured to use HTTPS
    # tlsSecretKeyRef:
    #   name: "<kubernetes.io/tls secret name>"

  security:
    authentication:
      modes: ["SCRAM"]

  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: <your-user-password>

# Secret holding the prometheus metrics endpoint HTTP Password.
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-endpoint-password
type: Opaque
stringData:
  password: <your-metrics-endpoint-password>
