FROM {{base_image}}


{% for file in files_to_add %}
ADD {{file}} {{file}}
{% endfor %}

ADD {{script_location}} {{script_location}}


{% block command -%}
CMD ["{{script_location}}", "{{ directories|join(' ') }}"]
{% endblock -%}
