{% extends "Dockerfile.template" %}

{% block build_binary -%}

# Copy the go source
COPY cmd/manager/main.go cmd/manager/main.go
COPY api/ api/
COPY controllers/ controllers/
COPY pkg/ pkg/
COPY build/bin/ build/bin/

# Build the operator
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager cmd/manager/main.go

{% endblock -%}

{% block build_second_stage -%}
FROM {{base_image}}

ENV OPERATOR=manager \
    USER_UID=1001 \
    USER_NAME=mongodb-kubernetes-operator

# Copy the operator binary and version manifest
WORKDIR /
COPY --from=builder /workspace/manager .
COPY --from=builder /workspace/build/bin /usr/local/bin

RUN  /usr/local/bin/user_setup

USER ${USER_UID}
{% endblock -%}

{% block command -%}
ENTRYPOINT ["/usr/local/bin/entrypoint"]
{% endblock -%}
