FROM {{base_image}}


{% for add in adds %}
ADD {{add}} {{add}}
{% endfor %}

ADD {{script_location}} {{script_location}}


{% block command -%}
CMD ["{{script_location}}", "{{ directories|join(' ') }}"]
{% endblock -%}
