{% extends "Dockerfile.template" %}

{% block build_binary -%}
# TODO: This build takes longer than it needs to and can still be optimized
RUN go build -o build/_output/bin/mongodb-kubernetes-operator github.com/mongodb/mongodb-kubernetes-operator/cmd/manager

ENV manifest_version=4.4
RUN mkdir -p /content/ \
        && chmod -R +r /content/ \
        && curl --fail --retry 3 -o /content/version_manifest.json "https://opsmanager.mongodb.com/static/version_manifest/${manifest_version}.json"
{% endblock -%}

{% block build_second_stage -%}
FROM {{base_image}}

ENV OPERATOR=/usr/local/bin/mongodb-kubernetes-operator \
    USER_UID=1001 \
    USER_NAME=mongodb-kubernetes-operator

# copy the operator binary and version manifest
COPY --from=builder /go/build/_output/bin/mongodb-kubernetes-operator ${OPERATOR}
COPY --from=builder /go/build/bin /usr/local/bin
COPY --from=builder /content/version_manifest.json /usr/local/version_manifest.json

RUN  /usr/local/bin/user_setup

USER ${USER_UID}
{% endblock -%}

{% block command -%}
ENTRYPOINT ["/usr/local/bin/entrypoint"]
{% endblock -%}
