kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e-test
subjects:
- kind: ServiceAccount
  name: e2e-test
  namespace: mongodb
roleRef:
  kind: ClusterRole
  name: e2e-test
  apiGroup: rbac.authorization.k8s.io
