FROM registry.access.redhat.com/ubi7/ubi

ARG agent_version
ARG tools_version

RUN yum update -y && rm -rf /var/cache/yum

RUN yum install -y  --disableplugin=subscription-manager -q curl \
    hostname nss_wrapper --exclude perl-IO-Socket-SSL procps \
    && yum upgrade -y -q \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p agent \
    && curl --fail --retry 3 --silent https://mciuploads.s3.amazonaws.com/mms-automation/mongodb-mms-build-agent/builds/automation-agent/prod/mongodb-mms-automation-agent-${agent_version}.rhel7_x86_64.tar.gz -o agent/mongodb-agent.tar.gz \
    && tar xfz agent/mongodb-agent.tar.gz \
    && mv mongodb-mms-automation-agent-*/mongodb-mms-automation-agent agent/mongodb-agent \
    && chmod +x agent/mongodb-agent \
    && mkdir -p /var/lib/automation/config \
    && chmod -R +r /var/lib/automation/config \
    && rm agent/mongodb-agent.tar.gz \
    && rm -r mongodb-mms-automation-agent-*

RUN mkdir -p /var/lib/mongodb-mms-automation \
    && mkdir -p /var/log/mongodb-mms-automation/ \
    && chmod -R +wr /var/log/mongodb-mms-automation/ \
    # ensure that the agent user can write the logs in OpenShift
    && touch /var/log/mongodb-mms-automation/readiness.log \
    && chmod ugo+rw /var/log/mongodb-mms-automation/readiness.log

## Install MongoDB tools. The agent will automatically search the folder and find the binaries.
RUN curl --fail --retry 3 --silent https://downloads.mongodb.org/tools/db/mongodb-database-tools-rhel70-x86_64-${tools_version}.tgz -o mongodb-tools.tgz \
    && tar xfz mongodb-tools.tgz --directory /var/lib/mongodb-mms-automation/ \
    && rm mongodb-tools.tgz

USER 2000
CMD ["agent/mongodb-agent", "-cluster=/var/lib/automation/config/automation-config.json"]
