#
# Docs: https://github.com/marketplace/actions/close-stale-issues
#
name: Close Stale Issues
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is being marked stale because it has been open for 60 days with no activity. Please comment if this issue is still affecting you. If there is no change, this issue will be closed in 30 days.'
          stale-pr-message: 'This PR is being marked stale because it has been open for 60 days with no activity. Please update the PR or ask for a fresh review.'
          close-issue-message: 'This issue was closed because it became stale and did not receive further updates. If the issue is still affecting you, please re-open it, or file a fresh Issue with updated information.'

          days-before-stale: 60
          days-before-close: 30
          days-before-pr-close: -1 # never close PRs

          exempt-issue-labels: 'bug,feature-request'
          ascending: true
